# Generated by Django 5.1.2 on 2024-10-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('route_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('route_name', models.CharField(max_length=255)),
                ('route_origin', models.CharField(max_length=255)),
                ('route_destination', models.CharField(max_length=255)),
                ('route_stop', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
