# Generated by Django 5.1.2 on 2024-10-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0002_remove_route_route_stop'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_stops',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='user_id',
            field=models.CharField(max_length=255),
        ),
    ]
