# Generated by Django 5.1.2 on 2024-10-21 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('route', '0002_remove_route_route_stop'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.CharField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('vehicle_id', models.IntegerField()),
                ('driver_name', models.CharField(max_length=255)),
                ('trip_distance', models.FloatField()),
                ('route_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.route')),
            ],
        ),
    ]
